const SEND_NEW_ROOM_MESSAGE = "SEND_NEW_ROOM";
const RECEIVE_NEW_ROOM_MESSAGE = "RECEIVE_NEW_MESSAGE_ROOM";
const LEAVE_ROOM = "LEAVE_ROOM";
const JOIN_ROOM = "JOIN_ROOM";
const JOIN_CHAT_ROOM = "JOIN_CHAT_ROOM";
const JOIN_CHAT_ROOM_MESSAGE = "JOIN_CHAT_ROOM_MESSAGE";
export default {
  SEND_NEW_ROOM_MESSAGE,
  RECEIVE_NEW_ROOM_MESSAGE,
  JOIN_ROOM,
  LEAVE_ROOM,
  JOIN_CHAT_ROOM,
  JOIN_CHAT_ROOM_MESSAGE,
};
